"""empty message

Revision ID: 39380bf0a64f
Revises: 
Create Date: 2019-12-16 01:24:41.220057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39380bf0a64f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orm_company', sa.Column('company_balance', sa.Integer(), nullable=False))
    op.add_column('orm_company', sa.Column('company_type', sa.String(length=45), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orm_company', 'company_type')
    op.drop_column('orm_company', 'company_balance')
    # ### end Alembic commands ###
